### ISSUE TITLE
jar 包从哪里下载啊？

### ISSUE THREAD

**Issue by cy920820** [zzcabc/Docker_Buildx_Danmuji#5]
![image](https://github.com/zzcabc/Docker_Buildx_Danmuji/assets/21211512/c7583dcd-939b-4c36-a1dd-bcc1f45eb54f)

**Comment by zzcabc** [comment]
你是用的项目中的docker compose 吗

**Comment by cy920820** [comment]
对的 是直接在源项目去下载jar 包？还是要自己构建？

**Comment by cy920820** [comment]
去源地址 release 下搞了一个，可以是吧
![image](https://github.com/zzcabc/Docker_Buildx_Danmuji/assets/21211512/fde2fae0-62ca-4143-846b-1d1c031a95ff)

**Comment by zzcabc** [comment]
```yaml
    build:
      context: .
      dockerfile: Dockerfile
```

请将docker-compose中的这段代码删除掉，遗留代码我忘记更新了
